## Install JDK
## Install Spark
## Set Environment variables
## Create a Spark Session

In [1]:
#Instalacja Sparka na colabie
!git clone https://github.com/djkormo/colab-examples.git

Cloning into 'colab-examples'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 121 (delta 44), reused 107 (delta 30), pack-reused 0
Receiving objects: 100% (121/121), 6.84 MiB | 1.58 MiB/s, done.
Resolving deltas: 100% (44/44), done.

In [2]:
!bash colab-examples/spark/install.bash

--2019-10-15 06:48:19--  http://apache.crihan.fr/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
Resolving apache.crihan.fr (apache.crihan.fr)... 195.221.21.36, 2001:660:7401:211::36
Connecting to apache.crihan.fr (apache.crihan.fr)|195.221.21.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 230091034 (219M) [application/x-gzip]
Saving to: ‘spark-2.4.4-bin-hadoop2.7.tgz’

spark-2.4.4-bin-had 100%[===================>] 219.43M  98.5MB/s    in 2.2s

2019-10-15 06:48:21 (98.5 MB/s) - ‘spark-2.4.4-bin-hadoop2.7.tgz’ saved [230091034/230091034]

Collecting spark-nlp
  Downloading https://files.pythonhosted.org/packages/f9/1a/711bde42e9cd17b5166a2c282ba9824103c416091c9ad95ca7dcece7170e/spark_nlp-2.2.2-py2.py3-none-any.whl
Installing collected packages: spark-nlp
Successfully installed spark-nlp-2.2.2

In [0]:
# based on https://www.tutorialspoint.com/pyspark/pyspark_sparkcontext.htm

import os
os.environ['JAVA_HOME'] = '/usr/lib/jvm/java-8-openjdk-amd64'
os.environ['SPARK_ME'] = '/content/spark-2.4.4-bin-hadoop2.7'

import findspark
findspark.init("spark-2.4.4-bin-hadoop2.7")

from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("First App") \
    .master("local[*]")\
    .getOrCreate()

In [0]:
from pyspark import SparkContext
sc = SparkContext.getOrCreate()

## Test Spark

In [5]:
df = spark.createDataFrame([{"Google": "Colab","Spark": "Scala"} ,{"Google": "Dataproc","Spark":"Python"}])
df.show()

spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/session.py:346: UserWarning: inferring schema from dict is deprecated,please use pyspark.sql.Row instead
  warnings.warn("inferring schema from dict is deprecated,"

+--------+------+
|  Google| Spark|
+--------+------+
|   Colab| Scala|
|Dataproc|Python|
+--------+------+

## Copy a data file to your local Colab environment

In [28]:
#!wget https://onedollarskill.s3.amazonaws.com/AI/retailstore.csv
!wget https://raw.githubusercontent.com/futurexskill/bigdata/master/retailstore.csv
!git clone https://github.com/futurexskill/bigdata.git

--2019-10-15 06:57:47--  https://raw.githubusercontent.com/futurexskill/bigdata/master/retailstore.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 279 [text/plain]
Saving to: ‘retailstore.csv.1’

retailstore.csv.1   100%[===================>]     279  --.-KB/s    in 0s

2019-10-15 06:57:47 (71.7 MB/s) - ‘retailstore.csv.1’ saved [279/279]

Cloning into 'bigdata'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 78 (delta 3), reused 0 (delta 0), pack-reused 69
Unpacking objects: 100% (78/78), done.

## Check if the file is copied

In [10]:
!ls

colab-examples	 sample_data		    spark-2.4.4-bin-hadoop2.7.tgz
retailstore.csv  spark-2.4.4-bin-hadoop2.7

# DataFrame

## Read the CSV file into a DataFrame

In [0]:
customerDF = spark.read.csv("retailstore.csv",header=True)

In [12]:
type(customerDF)

pyspark.sql.dataframe.DataFrame

## Print the dataset

In [13]:
customerDF.show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  18| 20000|  Male|Germany|        N|
|  19| 22000|Female| France|        N|
|  20| 24000|Female|England|        N|
|  21|  null|  Male|England|        N|
|  22| 50000|  Male| France|        Y|
|  23| 35000|Female|England|        N|
|  24|  null|  Male|Germany|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  27| 37000|Female| France|        N|
+----+------+------+-------+---------+

In [14]:
customerDF.show(5)

+---+------+------+-------+---------+
|Age|Salary|Gender|Country|Purchased|
+---+------+------+-------+---------+
| 18| 20000|  Male|Germany|        N|
| 19| 22000|Female| France|        N|
| 20| 24000|Female|England|        N|
| 21|  null|  Male|England|        N|
| 22| 50000|  Male| France|        Y|
+---+------+------+-------+---------+
only showing top 5 rows

## Get Statistical Summary of the DataFrame

In [15]:
customerDF.describe().show()

+-------+-----------------+-----------------+------+-------+---------+
|summary|              Age|           Salary|Gender|Country|Purchased|
+-------+-----------------+-----------------+------+-------+---------+
|  count|                9|                8|    10|     10|       10|
|   mean|22.11111111111111|          31875.0|  null|   null|     null|
| stddev|2.934469476943168|9818.895777311942|  null|   null|     null|
|    min|               18|            20000|Female|England|        N|
|    max|               27|            50000|  Male|Germany|        Y|
+-------+-----------------+-----------------+------+-------+---------+

## Select a particular column

In [16]:
customerDF.select("country").show()

+-------+
|country|
+-------+
|Germany|
| France|
|England|
|England|
| France|
|England|
|Germany|
| France|
|Germany|
| France|
+-------+

## View count group by country

In [17]:
customerDF.groupBy("country").count().show()

+-------+-----+
|country|count|
+-------+-----+
|Germany|    3|
| France|    4|
|England|    3|
+-------+-----+

## View count group by gender

In [18]:
customerDF.groupBy("gender").count().show()

+------+-----+
|gender|count|
+------+-----+
|Female|    5|
|  Male|    5|
+------+-----+

# Running SQL Queries Programmatically

## Create a temporary table

In [0]:
customerDF.createOrReplaceTempView("customer")

## Fetch all records from the table using a SQL query

In [0]:
results = spark.sql("select * from customer")

In [21]:
type(results)

pyspark.sql.dataframe.DataFrame

## Show the result fetched

In [22]:
results.show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  18| 20000|  Male|Germany|        N|
|  19| 22000|Female| France|        N|
|  20| 24000|Female|England|        N|
|  21|  null|  Male|England|        N|
|  22| 50000|  Male| France|        Y|
|  23| 35000|Female|England|        N|
|  24|  null|  Male|Germany|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  27| 37000|Female| France|        N|
+----+------+------+-------+---------+

## Get the list of customers with age greater than 22

In [23]:
new_results = spark.sql("select * from customer where age>22").show()

+---+------+------+-------+---------+
|Age|Salary|Gender|Country|Purchased|
+---+------+------+-------+---------+
| 23| 35000|Female|England|        N|
| 24|  null|  Male|Germany|        N|
| 25| 32000|Female| France|        Y|
| 27| 37000|Female| France|        N|
+---+------+------+-------+---------+

## Display the salary of customers with age greater than 22

In [24]:
new_results = spark.sql("select * from customer where age>22").select("salary").show()

+------+
|salary|
+------+
| 35000|
|  null|
| 32000|
| 37000|
+------+

## List of people earning more than 30000 with Spark DataFrame

In [25]:
customerDF.filter("salary > 30000").show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  22| 50000|  Male| France|        Y|
|  23| 35000|Female|England|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  27| 37000|Female| France|        N|
+----+------+------+-------+---------+

## List of people earning more than 200K with Spark SQL

In [26]:
spark.sql("select * from customer where salary > 30000").show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  22| 50000|  Male| France|        Y|
|  23| 35000|Female|England|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  27| 37000|Female| France|        N|
+----+------+------+-------+---------+

## Group By gender find average salary and max age

In [27]:
customerDF.groupBy("gender").agg({"salary": "avg", "age": "max"}).show()

+------+-----------+--------+
|gender|avg(salary)|max(age)|
+------+-----------+--------+
|Female|    30000.0|      27|
|  Male|    35000.0|      24|
+------+-----------+--------+

## Fetch Multiple Columns

In [0]:
customerDF.select(["age","salary"]).show()

+----+------+
| age|salary|
+----+------+
|  18| 20000|
|  19| 22000|
|  20| 24000|
|  21|  null|
|  22| 50000|
|  23| 35000|
|  24|  null|
|  25| 32000|
|null| 35000|
|  27| 37000|
+----+------+

## Adding a new column

In [0]:
customerDF.withColumn('doublesalary',customerDF['salary']*2).show()

+----+------+------+-------+---------+------------+
| Age|Salary|Gender|Country|Purchased|doublesalary|
+----+------+------+-------+---------+------------+
|  18| 20000|  Male|Germany|        N|     40000.0|
|  19| 22000|Female| France|        N|     44000.0|
|  20| 24000|Female|England|        N|     48000.0|
|  21|  null|  Male|England|        N|        null|
|  22| 50000|  Male| France|        Y|    100000.0|
|  23| 35000|Female|England|        N|     70000.0|
|  24|  null|  Male|Germany|        N|        null|
|  25| 32000|Female| France|        Y|     64000.0|
|null| 35000|  Male|Germany|        N|     70000.0|
|  27| 37000|Female| France|        N|     74000.0|
+----+------+------+-------+---------+------------+

## Renaming a column

In [0]:
customerDF.withColumnRenamed('salary', 'income').show()

+----+------+------+-------+---------+
| Age|income|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  18| 20000|  Male|Germany|        N|
|  19| 22000|Female| France|        N|
|  20| 24000|Female|England|        N|
|  21|  null|  Male|England|        N|
|  22| 50000|  Male| France|        Y|
|  23| 35000|Female|England|        N|
|  24|  null|  Male|Germany|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  27| 37000|Female| France|        N|
+----+------+------+-------+---------+

## Age of people earning more than 30000

In [0]:
customerDF.filter("salary > 30000").select('age').show()

+----+
| age|
+----+
|  22|
|  23|
|  25|
|null|
|  27|
+----+

## Age & country of people earning more than 200K

In [0]:
customerDF.filter("salary > 30000").select('age','country').show()

+----+-------+
| age|country|
+----+-------+
|  22| France|
|  23|England|
|  25| France|
|null|Germany|
|  27| France|
+----+-------+

## Fetching data with Python comparision operator

In [0]:
customerDF.filter(customerDF['salary'] > 30000).show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  22| 50000|  Male| France|        Y|
|  23| 35000|Female|England|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  27| 37000|Female| France|        N|
+----+------+------+-------+---------+

In [0]:

customerDF.filter(customerDF['salary'] > 30000).select('age','country').show()

+----+-------+
| age|country|
+----+-------+
|  22| France|
|  23|England|
|  25| France|
|null|Germany|
|  27| France|
+----+-------+

## Applying multiple Filter conditions

In [0]:
customerDF.filter((customerDF['salary'] > 30000) & (customerDF['age'] < 25)).show()

+---+------+------+-------+---------+
|Age|Salary|Gender|Country|Purchased|
+---+------+------+-------+---------+
| 22| 50000|  Male| France|        Y|
| 23| 35000|Female|England|        N|
+---+------+------+-------+---------+

## ~ is a not operation

In [0]:
customerDF.filter((customerDF['salary'] > 30000) & ~(customerDF['age'] < 22)).show()

+---+------+------+-------+---------+
|Age|Salary|Gender|Country|Purchased|
+---+------+------+-------+---------+
| 22| 50000|  Male| France|        Y|
| 23| 35000|Female|England|        N|
| 25| 32000|Female| France|        Y|
| 27| 37000|Female| France|        N|
+---+------+------+-------+---------+

## Count Distrinct, Average and Standard Deviation

In [0]:
from pyspark.sql.functions import countDistinct, avg,stddev

## count distinct countries

In [0]:
customerDF.select(countDistinct("country")).show()

+-----------------------+
|count(DISTINCT country)|
+-----------------------+
|                      3|
+-----------------------+

## Use alias

In [0]:
customerDF.select(countDistinct("country").alias("Distinct Countries")).show()

+------------------+
|Distinct Countries|
+------------------+
|                 3|
+------------------+

## Calculate avergage income

In [0]:
customerDF.select(avg('salary')).show()

+-----------+
|avg(salary)|
+-----------+
|    31875.0|
+-----------+

## Calculate avergage age

In [0]:
customerDF.select(avg('age')).show()

+-----------------+
|         avg(age)|
+-----------------+
|22.11111111111111|
+-----------------+

## Calculate standard deviation

In [0]:
customerDF.select(stddev("salary")).show()

+-------------------+
|stddev_samp(salary)|
+-------------------+
|  9818.895777311942|
+-------------------+

In [0]:
customerDF.select(stddev("age")).show()

+-----------------+
| stddev_samp(age)|
+-----------------+
|2.934469476943168|
+-----------------+

## format number

In [0]:
from pyspark.sql.functions import format_number

In [0]:
salary_std = customerDF.select(stddev("salary").alias('std'))

In [0]:
salary_std.show()

+-----------------+
|              std|
+-----------------+
|9818.895777311942|
+-----------------+

In [0]:
salary_std.select(format_number('std',2)).show()

+---------------------+
|format_number(std, 2)|
+---------------------+
|             9,818.90|
+---------------------+

## Order By

Order By Ascending

In [0]:
customerDF.orderBy("salary").show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  21|  null|  Male|England|        N|
|  24|  null|  Male|Germany|        N|
|  18| 20000|  Male|Germany|        N|
|  19| 22000|Female| France|        N|
|  20| 24000|Female|England|        N|
|  25| 32000|Female| France|        Y|
|null| 35000|  Male|Germany|        N|
|  23| 35000|Female|England|        N|
|  27| 37000|Female| France|        N|
|  22| 50000|  Male| France|        Y|
+----+------+------+-------+---------+

Order by descending

In [0]:
customerDF.orderBy(customerDF["salary"].desc()).show()

+----+------+------+-------+---------+
| Age|Salary|Gender|Country|Purchased|
+----+------+------+-------+---------+
|  22| 50000|  Male| France|        Y|
|  27| 37000|Female| France|        N|
|  23| 35000|Female|England|        N|
|null| 35000|  Male|Germany|        N|
|  25| 32000|Female| France|        Y|
|  20| 24000|Female|England|        N|
|  19| 22000|Female| France|        N|
|  18| 20000|  Male|Germany|        N|
|  21|  null|  Male|England|        N|
|  24|  null|  Male|Germany|        N|
+----+------+------+-------+---------+

## drop any row that contains null data

In [0]:
customerDF.na.drop().show()

+---+------+------+-------+---------+
|Age|Salary|Gender|Country|Purchased|
+---+------+------+-------+---------+
| 18| 20000|  Male|Germany|        N|
| 19| 22000|Female| France|        N|
| 20| 24000|Female|England|        N|
| 22| 50000|  Male| France|        Y|
| 23| 35000|Female|England|        N|
| 25| 32000|Female| France|        Y|
| 27| 37000|Female| France|        N|
+---+------+------+-------+---------+

## Replace missing values

In [0]:
customerDF.na.fill('NEW VALUE').show()

+---------+---------+------+-------+---------+
|      Age|   Salary|Gender|Country|Purchased|
+---------+---------+------+-------+---------+
|       18|    20000|  Male|Germany|        N|
|       19|    22000|Female| France|        N|
|       20|    24000|Female|England|        N|
|       21|NEW VALUE|  Male|England|        N|
|       22|    50000|  Male| France|        Y|
|       23|    35000|Female|England|        N|
|       24|NEW VALUE|  Male|Germany|        N|
|       25|    32000|Female| France|        Y|
|NEW VALUE|    35000|  Male|Germany|        N|
|       27|    37000|Female| France|        N|
+---------+---------+------+-------+---------+